"""Agent model - registered monitoring agents."""
from datetime import datetime
from sqlalchemy import Column, String, Integer, DateTime
from sqlalchemy.orm import relationship

from ..database import Base


class Agent(Base):
    """Registered agent that reports monitoring results to server."""
    
    __tablename__ = "agents"
    
    id = Column(String, primary_key=True)  # UUID generated by agent
    name = Column(String, nullable=True)  # Friendly name set by admin
    secret_hash = Column(String, nullable=False)  # Hashed shared secret
    approved = Column(Integer, default=0)  # 0=pending, 1=approved, -1=rejected
    last_seen = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationship to monitors
    monitors = relationship("Monitor", back_populates="agent")
    
    @property
    def status(self) -> str:
        """Get approval status as string."""
        if self.approved == 1:
            return "approved"
        elif self.approved == -1:
            return "rejected"
        return "pending"
